/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication19;

import java.awt.CardLayout;
import java.io.IOException;
import java.net.Socket;
import javax.swing.JPanel;
import com.google.gson.*;
import java.awt.Color;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.border.Border;

/**
 *
 * @author Saurabh
 */
public class issue_desc extends javax.swing.JPanel {

    /**
     * Creates new form issue_desc
     */
    JPanel base_panel;
    Socket soc;
    String uname;
    Main_list_panel lpn ;
    public issue_desc() {
        
        initComponents();
    }
    
    public issue_desc(JPanel base,Main_list_panel lp) {
        base_panel = base;
        lpn = lp;
        initComponents();
    }
    
    void setsocket(Socket soc) throws IOException
    {
    this.soc = soc;
    }
     void setuname(String uname)
     {
     this.uname = uname;
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        down = new javax.swing.JButton();
        rating = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        comment_b = new javax.swing.JList<>();
        title = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comment_button = new javax.swing.JButton();
        up = new javax.swing.JButton();
        comment_l = new javax.swing.JLabel();
        date_l = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        subject = new javax.swing.JLabel();
        status_l = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        iid = new javax.swing.JLabel();
        subjectcombo = new javax.swing.JComboBox<>();
        submit = new javax.swing.JButton();
        make = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setLayout(null);

        description.setColumns(20);
        description.setRows(5);
        jScrollPane1.setViewportView(description);

        add(jScrollPane1);
        jScrollPane1.setBounds(199, 153, 570, 130);

        jLabel3.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Title");
        jLabel3.setAutoscrolls(true);
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel3);
        jLabel3.setBounds(81, 109, 100, 30);

        jLabel2.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Subject");
        jLabel2.setAutoscrolls(true);
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel2);
        jLabel2.setBounds(81, 65, 100, 30);

        down.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication19/d.png"))); // NOI18N
        down.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downActionPerformed(evt);
            }
        });
        add(down);
        down.setBounds(310, 310, 30, 30);
        add(rating);
        rating.setBounds(199, 303, 70, 40);

        comment_b.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(comment_b);

        add(jScrollPane2);
        jScrollPane2.setBounds(79, 397, 690, 155);

        title.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleActionPerformed(evt);
            }
        });
        add(title);
        title.setBounds(199, 112, 570, 30);

        jLabel1.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Rating");
        jLabel1.setAutoscrolls(true);
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel1);
        jLabel1.setBounds(79, 303, 100, 40);

        jLabel4.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Description");
        jLabel4.setAutoscrolls(true);
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel4);
        jLabel4.setBounds(79, 153, 100, 30);

        comment_button.setText("Comment");
        comment_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comment_buttonActionPerformed(evt);
            }
        });
        add(comment_button);
        comment_button.setBounds(668, 572, 101, 23);

        up.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication19/u.png"))); // NOI18N
        up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upActionPerformed(evt);
            }
        });
        add(up);
        up.setBounds(270, 310, 30, 30);

        comment_l.setText("Comments:");
        add(comment_l);
        comment_l.setBounds(50, 361, 100, 30);

        date_l.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        date_l.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        date_l.setText("Date");
        date_l.setAutoscrolls(true);
        date_l.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(date_l);
        date_l.setBounds(420, 310, 100, 30);
        add(date);
        date.setBounds(540, 310, 150, 30);

        jButton4.setText("< Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4);
        jButton4.setBounds(710, 10, 90, 30);
        add(subject);
        subject.setBounds(200, 70, 130, 30);

        status_l.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        status_l.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        status_l.setText("Status");
        status_l.setAutoscrolls(true);
        status_l.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(status_l);
        status_l.setBounds(400, 30, 100, 30);
        add(status);
        status.setBounds(510, 30, 150, 30);

        jLabel9.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Issue ID");
        jLabel9.setAutoscrolls(true);
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel9);
        jLabel9.setBounds(81, 24, 100, 30);
        add(iid);
        iid.setBounds(200, 30, 150, 30);

        subjectcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NONE","ISEE", "SEPM", "DBMS", "TOC"}));
        subjectcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectcomboActionPerformed(evt);
            }
        });
        add(subjectcombo);
        subjectcombo.setBounds(200, 70, 120, 30);

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        add(submit);
        submit.setBounds(630, 340, 90, 30);

        make.setText("Make Changes");
        make.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeActionPerformed(evt);
            }
        });
        add(make);
        make.setBounds(660, 340, 130, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void comment_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comment_buttonActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_comment_buttonActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) base_panel.getLayout();
       cardLayout.show(base_panel,"card2");
       base_panel.setSize(842, 610);
       
               try {
                lpn.refresh_list();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
            }  
    }//GEN-LAST:event_jButton4ActionPerformed

    private void subjectcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectcomboActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_subjectcomboActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
            // TODO add your handling code here:
            
            Border border = BorderFactory.createLineBorder(Color.red);
            Border bor = BorderFactory.createLineBorder(Color.BLACK);
            
              subjectcombo.setBorder(bor);
            title.setBorder(bor);
            description.setBorder(null);
            
            if(subjectcombo.getSelectedItem().equals("NONE"))
             subjectcombo.setBorder(border);
            else if(title.getText().equals(""))
            title.setBorder(border);
            else if(description.getText().equals(""))
            description.setBorder(border);
            else
            {
            issue s = new issue();
            s.UID = uname;
            s.Title = title.getText();
            s.Description = description.getText();
            s.Subject =  subjectcombo.getSelectedItem().toString();
            s.IID = iid.getText();
            s.rating = 0;
            s.Status = status.getText();
            Gson g = new Gson();
            String send = g.toJson(s);
            
        try {
            DataInputStream din=new DataInputStream(soc.getInputStream());
            DataOutputStream dos = new DataOutputStream(soc.getOutputStream());
            
             dos.writeUTF("3");
             dos.flush();
             dos.writeUTF(send);
             dos.flush();
            
        } catch (IOException ex) {
            Logger.getLogger(issue_desc.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            
            CardLayout cardLayout = (CardLayout) base_panel.getLayout();
       cardLayout.show(base_panel,"card2");
       base_panel.setSize(842, 610);
       
             try {
                lpn.refresh_list();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
            }
             
             subjectcombo.setBorder(bor);
            title.setBorder(bor);
            description.setBorder(null);
        }
            
    }//GEN-LAST:event_submitActionPerformed

    private void titleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_titleActionPerformed

    private void upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upActionPerformed
        // TODO add your handling code here:
        up.setVisible(false);
        down.setVisible(false);
        
        vote v = new vote();
        v.UID = uname;
        v.IID = lpn.selected.IID;
        
        Gson g = new Gson();
            String send = g.toJson(v);
            
        try {
            DataInputStream din=new DataInputStream(soc.getInputStream());
            DataOutputStream dos = new DataOutputStream(soc.getOutputStream());
            
             dos.writeUTF("5");
             dos.flush();
            
             Integer i = lpn.selected.rating;
        i++;
        rating.setText(i.toString());
        
       
            
             dos.writeUTF(lpn.selected.IID);
             dos.flush();
             dos.writeUTF("up");
             dos.flush();
             dos.writeUTF(send);
             dos.flush();
             
        } catch (IOException ex) {
            Logger.getLogger(issue_desc.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }//GEN-LAST:event_upActionPerformed

    private void downActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downActionPerformed
        // TODO add your handling code here:
               up.setVisible(false);
        down.setVisible(false);
        
        vote v = new vote();
        v.UID = uname;
        v.IID = lpn.selected.IID;
        
        Gson g = new Gson();
            String send = g.toJson(v);
            
        try {
            DataInputStream din=new DataInputStream(soc.getInputStream());
            DataOutputStream dos = new DataOutputStream(soc.getOutputStream());
            
             dos.writeUTF("5");
             dos.flush();
            
             Integer i = lpn.selected.rating;
        i--;
        rating.setText(i.toString());
        
       
            
             dos.writeUTF(lpn.selected.IID);
             dos.flush();
             dos.writeUTF("down");
             dos.flush();
             dos.writeUTF(send);
             dos.flush();
             
        } catch (IOException ex) {
            Logger.getLogger(issue_desc.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         
        
    }//GEN-LAST:event_downActionPerformed

    private void makeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeActionPerformed
        // TODO add your handling code here:
          Border border = BorderFactory.createLineBorder(Color.red);
            Border bor = BorderFactory.createLineBorder(Color.BLACK);
            
              subjectcombo.setBorder(bor);
            title.setBorder(bor);
            description.setBorder(null);
            
            if(subjectcombo.getSelectedItem().equals("NONE"))
             subjectcombo.setBorder(border);
            else if(title.getText().equals(""))
            title.setBorder(border);
            else if(description.getText().equals(""))
            description.setBorder(border);
            else
            {
        CardLayout cardLayout = (CardLayout) base_panel.getLayout();
       cardLayout.show(base_panel,"card2");
       base_panel.setSize(842, 610);
       
     issue is = new issue();
     is.IID = iid.getText();
     is.Subject  = subjectcombo.getSelectedItem().toString();
     is.Title = title.getText();
     is.Description = description.getText();
     
     Gson g = new Gson();
     
    
        try {
             DataOutputStream dos = new DataOutputStream(soc.getOutputStream());
             dos.writeUTF("6");
             dos.flush();
             String o = g.toJson(is);
             dos.writeUTF(o);
             dos.flush();
        } catch (IOException ex) {
            Logger.getLogger(issue_desc.class.getName()).log(Level.SEVERE, null, ex);
        }
            
                try {
                lpn.refresh_list();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
            }
                
                
                 subjectcombo.setBorder(bor);
            title.setBorder(bor);
            description.setBorder(null); 
        }
            

    }//GEN-LAST:event_makeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JList<String> comment_b;
    public javax.swing.JButton comment_button;
    public javax.swing.JLabel comment_l;
    public javax.swing.JLabel date;
    private javax.swing.JLabel date_l;
    public javax.swing.JTextArea description;
    public javax.swing.JButton down;
    public javax.swing.JLabel iid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JButton make;
    public javax.swing.JLabel rating;
    public javax.swing.JLabel status;
    private javax.swing.JLabel status_l;
    public javax.swing.JLabel subject;
    public javax.swing.JComboBox<String> subjectcombo;
    public javax.swing.JButton submit;
    public javax.swing.JTextField title;
    public javax.swing.JButton up;
    // End of variables declaration//GEN-END:variables
}
